In [2]:
import torch

In [3]:
print('CUDA is using - ', torch.cuda.is_available())

CUDA is using -  False


**Tensors**

In [4]:
torch.rand(2, 2)

tensor([[0.1661, 0.6370],
        [0.1975, 0.0124]])

In [6]:
x = torch.tensor([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
x[0][1] = 5 #NOT numpy notation!
x

tensor([[0, 5, 0],
        [1, 1, 1],
        [2, 2, 2]])

In [7]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [12]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(1)

tensor([0.4088])

In [15]:
torch.rand(1).item() #Only for zero rang tensors

0.3536630868911743

**Basic tensors operations**

min, max, argmax, argmin

In [16]:
torch.rand(2, 2).max()

tensor(0.6228)

In [17]:
torch.rand(2, 2).max().item()

0.5521793365478516

Change tensor type

In [19]:
long_tensor = torch.tensor([[0, 0, 1], [1, 1, 1], [0, 0, 0]])
long_tensor.type()

'torch.LongTensor'

In [20]:
float_tensor = long_tensor.to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

Inplace operations

In [22]:
random_tensor = torch.rand(2, 2)
random_tensor.log2_() # _ symbol means inplace operation

tensor([[-0.3393, -1.7529],
        [-1.6955, -0.2094]])

In [23]:
random_tensor # yep, operation was inplace

tensor([[-0.3393, -1.7529],
        [-1.6955, -0.2094]])

Reshaping

In [26]:
# Can do it with view or reshape
flat_tensor = torch.rand(784)
print(flat_tensor.view(1, 28, 28).shape)
print(flat_tensor.reshape(1, 28, 28).shape)

torch.Size([1, 28, 28])
torch.Size([1, 28, 28])


In [27]:
# Reshape is better, because of stability (see torch.contiguous() problem)