In [1]:
import torch

In [2]:
print('CUDA is using - ', torch.cuda.is_available())

CUDA is using -  False


**Tensors**

In [3]:
torch.rand(2, 2)

tensor([[0.1408, 0.5553],
        [0.5820, 0.1066]])

In [4]:
x = torch.tensor([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
x[0][1] = 5 #NOT numpy notation!
x

tensor([[0, 5, 0],
        [1, 1, 1],
        [2, 2, 2]])

In [5]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [6]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(1)

tensor([0.7916])

In [8]:
torch.rand(1).item() #Only for zero rang tensors

0.5251708626747131

**Basic tensors operations**

min, max, argmax, argmin

In [9]:
torch.rand(2, 2).max()

tensor(0.9958)

In [10]:
torch.rand(2, 2).max().item()

0.8044725656509399

Change tensor type

In [11]:
long_tensor = torch.tensor([[0, 0, 1], [1, 1, 1], [0, 0, 0]])
long_tensor.type()

'torch.LongTensor'

In [12]:
float_tensor = long_tensor.to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

Inplace operations

In [13]:
random_tensor = torch.rand(2, 2)
random_tensor.log2_() # _ symbol means inplace operation

tensor([[-0.4307, -1.6090],
        [-0.9655, -1.5856]])

In [14]:
random_tensor # yep, operation was inplace

tensor([[-0.4307, -1.6090],
        [-0.9655, -1.5856]])

Reshaping

In [15]:
# Can do it with view or reshape
flat_tensor = torch.rand(784)
print(flat_tensor.view(1, 28, 28).shape)
print(flat_tensor.reshape(1, 28, 28).shape)

torch.Size([1, 28, 28])
torch.Size([1, 28, 28])


In [27]:
# Reshape is better, because of stability (see torch.contiguous() problem)